### ISSUE TITLE
Aggregate sealed secrets to admin cluster role

### ISSUE THREAD

**Issue by chetan-rns** [disposab1e/sealed-secrets-operator-helm#14]
On OpenShift the sealed secrets resource is not aggregated to the admin cluster role. This prevents service accounts (eg Argo CD) from managing sealed secret resources even though they have admin privileges in that namespace   This could be achieved by adding the label 

```yaml
"rbac.authorization.k8s.io/aggregate-to-admin": "true",

**Comment by disposab1e** [comment]
Thx for reporting! Do you think https://github.com/bitnami-labs/sealed-secrets/pull/540 
`rbac.authorization.k8s.io/aggregate-to-edit: "true"`
can be useful too?

**Comment by chetan-rns** [comment]
Yes @disposab1e. It would better if we can include view as well
```yaml
rbac.authorization.k8s.io/aggregate-to-view: "true"
rbac.authorization.k8s.io/aggregate-to-edit: "true"
rbac.authorization.k8s.io/aggregate-to-admin: "true"
```
